### ISSUE TITLE
Proposal Review

### ISSUE THREAD

**Issue by Chris210634** [riteshr19/Uber-Ride-Demand-and-Pricing-Analysis#1]
Sounds like an interesting project. Here's my feedback:

 - You say you want to predict the number of uber rides based on some features. I'm curious as to how you want to do this. Normally, what we want to predict is a column in the data matrix. Here, the number of uber rides is not, since each uber ride is a row in the table.
 - It's unclear to me how you will get pricing data. I did not see this in the Kaggle dataset. It's unclear how you would optimize pricing.

**Comment by msyd6** [comment]
Thank you for your feedback regarding our project!

To clarify, our dataset represents each Uber ride as a row with various features, and you are correct that typically the target variable, or what we aim to predict, should be a column in this matrix. However, in our analysis, the "number of Uber rides" is indeed a calculated feature, aggregated based on certain criteria such as location, time, or specific conditions. Here's how our data is structured:

Time: Timestamp of when the ride occurred
Location: Starting or ending location of the ride
DriverID: Identifier for the driver
Weather: Conditions at the time of the ride
Price: Cost of the ride
For instance, suppose we want to predict the number of rides in a specific area during a particular time frame. We aggregate the data by the time and location to create a new dataset where each row corresponds to a particular time and location, and a new column, Number_of_Rides, represents the count of rides for those specific conditions.

This aggregated view then serves as the input for our predictive models, where Number_of_Rides becomes the target variable. The model aims to forecast this count based on features like average price, weather conditions, and location-time specifics.

I hope this clears up any confusion regarding our dataset's structure and how we intend to use it for making predictions. Please let me know if there are more details I can provide or if further clarifications are needed for this!

Regarding your second point, the pricing data is available in the Kaggle dataset. You might have missed it, which is understandable. I have attached a screenshot of the dataset showing the pricing. Please take a look.

And let us know if there are any other issues that need to be addressed as well. Thank you!

<img width="1311" alt="Screenshot 2024-10-09 at 5 03 18 PM" src="https://github.com/user-attachments/assets/6a6d391c-5ba4-48b4-9ba6-53558edcc3fc">

**Comment by riteshr19** [comment]
@msyd6, thanks for the clarification!

@Chris210634, if you need more clarification, let us know!
